### PR TITLE
fix problem loading the widget on mobile devices, mousemove event doesnt works on mobile

### PR DESCRIPTION
**Pull request by acoalex**
Loading widget on page ready event the widget will load  on any device

### CODE REVIEW

**Comment by magiccart** [comment]
Thanks for your pull. I think should add "touchstart" same like as here $("body").one("mousemove touchstart", function() {
I don't want use $(document).ready(function() { because this will run crisp after site loaded so will cause down google scores speed if you If google speed is important with your website.

**Comment by acoalex** [comment]
Thanks, I imagined that this option was due to Google ranking issues. 
Cheers!

**Comment by magiccart** [comment]
If ok please help me with the new pull I will merge it. 
Thanks for contributed.

**Comment by acoalex** [comment]
Done!

**Pull request merged**
